"""add password reset token

Revision ID: 43628a5f9da9
Revises: 8cfaa274526d
Create Date: 2026-08-21 13:26:32.462880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43628a5f9da9'
down_revision = '8cfaa274526d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['password_reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
